### ISSUE TITLE
[7.0.0-alpha.1] EnsureCreated need to be called twice

### ISSUE THREAD

**Issue by Merilix** [bubibubi/EntityFrameworkCore.Jet#135]
The first call will create an empty database file but raises an exception.
The second call will successful apply migrations so the db becomes ready to use.

Code to reproduce:
```
        private void btEnsureCreated_Click(object sender, EventArgs e)
        {
            try
            {
                using (var db = new BloggingContext())
                    db.Database.EnsureCreated();
            }
            catch (Exception ex) 
            { 
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }

            using (var db = new BloggingContext())
                db.Database.EnsureCreated();
        }
```

Context :
``` 
   protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options
        .LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information)
        .EnableSensitiveDataLogging()
        .UseConfigurationManager()
        .UseJetOleDb("Name=bloggingDb");
```
app.config:
```
  <connectionStrings>
    <add 
      name="bloggingDb" 
      providerName=".NET Framework-Datenanbieter für OLE DB"
      connectionString="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=blogging.accdb"/>
  </connectionStrings>
```
Raised Exception & Stacktrace:
```
To use ODBC in conjunction with Jet, please reference the 'System.Data.Odbc' (version >= 6.0.0) NuGet package.
   at EntityFrameworkCore.Jet.Data.JetFactory.GetDataAccessProviderFactory(DataAccessProviderType dataAccessProviderType)
   at EntityFrameworkCore.Jet.Data.JetConnection.CreateDatabase(String fileNameOrConnectionString, DatabaseVersion version, CollatingOrder collatingOrder, String databasePassword, SchemaProviderType schemaProviderType)
   at EntityFrameworkCore.Jet.Data.JetStoreSchemaDefinition.JetStoreDatabaseHandling.ProcessDatabaseOperation(JetCommand command)
   at EntityFrameworkCore.Jet.Data.JetCommand.ExecuteNonQueryCore()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at EntityFrameworkCore.Jet.Storage.Internal.JetDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Test_EntityFrameworkCore.Jet._6.Form1.btEnsureCreated_Click(Object sender, EventArgs e) in G:\Users\Frank\Source\Repos\Test-EntityFrameworkCore.Jet.6\Test-EntityFrameworkCore.Jet.6\Form1.cs:line 90
```

Packages:
```
  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.ConfigurationManager" Version="2.0.0" />
    <PackageReference Include="EntityFrameworkCore.Jet" Version="7.0.0-alpha.1" />
    <PackageReference Include="EntityFrameworkCore.Jet.OleDb" Version="7.0.0-alpha.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
  </ItemGroup>
```

I don't know if thats relevant:
The DAO Engine is a 64bit standalone Install (AccessDatabaseEngine_X64.exe, OFFICE16 from MS) whilst I'm still using Access2007 32bit on that machine without any further problems; even if I use the very same database from Access2007 and .Net at the same time.

**Comment by ChrisJollyAU** [comment]
Simply put it looks like you have an invalid connection string.

You are configuring it with the connection string of `"Name=bloggingDb"`. This is not a specific provider format (OleDb or Odbc) and so is being treated as a simple file name.

During the database create, it is needing to know whether we are needing to use OleDb or Odbc. This is done via using the connection string. As it does not match a valid OleDb or Odbc connection string, it goes to use the default provider which is set to Odbc.

As you don't have `System.Data.Odbc` referenced you get the error.

By the looks of it the file does get created (I suspect you might find a file literally named `Name=bloggingdb`) before it encounters the error. For the second call, as the file is already created, it just needs to open it so that works fine.


--
Just noticed you have referenced `EntityFrameworkCore.ConfigurationManager`. Had to look it up as I am unfamilar with that extemsion. I can see that it is meant to automatically resolve the connection string from the provided name and look it up with the ConfigurationManager. Will need to have a look to see if the connection string is getting resolved before hitting EFCore.Jet or as it looks like it may be getting the raw unresolved connection string

--

Actually, you may not need that extension. EF Core appears to have that sort of behaviour built in by default

--

I suspect it will be fine if you get the connection string your self such as

`.UseJetOleDb(ConfigurationManager.ConnectionStrings["bloggingDb"].ConnectionString);`

See https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings for more info

--

I will still create a sample project this week to test and see if my theory is correct and if there is any ordering issues or such regarding when the connection string gets resolved

**Comment by Merilix** [comment]
My Connectionstrings are ok. The issue occurs even if I provide the string directly via `.UseJetOleDb($"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=blogging.accdb");`.  Everything else except creating a new Database in code is fine and works well.

The described issue seem to be the same as #122.
...
After some further investigation (debugging via dnspy) I found the problem is caused by the way JetConnection.CreateDatabase is called / used internally. JetConnection.CreateDatabase is static, has no info about the provider factory and tries to extract that info from the given filename. Doesnt work because just the filename, not the whole connection string is passed even if the caller EntityFrameworkCore.Jet.Data.JetStoreSchemaDefinition.ProcessDatabaseOperation had that info (via parameter).

As a consequence, Odbc will be used as default but fails.
